version: '3'

services:
  emulated_hue:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
      target: dev_vscode
    restart: "no"
    environment:
      - DATA_DIR=/config
      # - IP=127.0.0.1
      # - MAC=00:00:00:00:00:00
      - VERBOSE=True
    volumes:
      - ..:/workspace
      - ../config:/config
    network_mode: "host"
    command: /bin/sh -c "while sleep 1000; do :; done"
