version: '3'

services:
  emulated_hue:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
      target: dev_pycharm
    restart: "no"
    environment:
      - DATA_DIR=/config
      # - IP=127.0.0.1
      # - MAC=00:00:00:00:00:00
      - VERBOSE=True
    volumes:
      - ../config:/config
#   network_mode: "host"
#   Host networking seems to freeze pycharm's debugger
    ports:
      - '80:80'
      - '443:443'
      - '1900:1900/udp'
      - '2100:2100/udp'
