name: Docker Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    strategy:
      matrix:
        include:
          - arch: linux/386
            arch_friendly: i386
          - arch: linux/amd64
            arch_friendly: amd64
          - arch: linux/arm/v6
            arch_friendly: armv6
          - arch: linux/arm/v7
            arch_friendly: armv7
          - arch: linux/arm64
            arch_friendly: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.test
          platforms: ${{ matrix.arch }}
          load: true
          tags: hass_emulated_hue:ci-${{ matrix.arch_friendly }}

      - name: Inspect
        run: |
          docker images
          docker image inspect test:ci
